### ISSUE TITLE
Updating to CentOS 6.7

### ISSUE THREAD

**Issue by hugoboos** [iuscommunity-pkg/php56u-pecl-imagick#1]
When updating CentOS 6.6 to 6.7 the resolving of the dependencies fails.

```
Error: Package: php56u-pecl-imagick-3.1.2-5.ius.centos6.x86_64 (@ius)
           Requires: libMagickCore.so.2()(64bit)
           Removing: ImageMagick-6.5.4.7-7.el6_5.x86_64 (@base)
               libMagickCore.so.2()(64bit)
           Updated By: ImageMagick-6.7.2.7-2.el6.x86_64 (base)
               Not found
Error: Package: php56u-pecl-imagick-3.1.2-5.ius.centos6.x86_64 (@ius)
           Requires: libMagickWand.so.2()(64bit)
           Removing: ImageMagick-6.5.4.7-7.el6_5.x86_64 (@base)
               libMagickWand.so.2()(64bit)
           Updated By: ImageMagick-6.7.2.7-2.el6.x86_64 (base)
               Not found
```

**Comment by b-harper** [comment]
Hello @hugoboos,

Thanks for taking the time to reach out regarding this issue.  We discovered and patched this issue when Red Hat released RHEL 6.7[0].  We were waiting to push the patch to the IUS CentOS repos till CentOS released 6.7.  Looks like they did that today.  We will work on getting updated packages into the stable repos ASAP.

-Ben
[0] https://lists.launchpad.net/ius-community/msg01566.html

**Comment by hugoboos** [comment]
Thanks.

**Comment by b-harper** [comment]
The IUS master mirror has been updated with new php5*-pecl-imagick packages.  Please note, it can take up to 24 hours for all the public mirrors to get updated.
