### ISSUE TITLE
No module for php-zts

### ISSUE THREAD

**Issue by ghost** [iuscommunity-pkg/php56u-pecl-imagick#2]
After installing this package I discovered that it did not include a version of imagick.so for php-zts. Every other module we're using installs a binary to both /usr/lib64/php and /usr/lib64/php-zts. We're using Apache 2 mpm.worker on RHEL 6.7 in our environment and so have to run php-zts for compatibility. NOTE: This may be a shortcoming in the upstream source, as the latest stock php-pecl-imagick package for Fedora 22 is also missing support for zts.

**Comment by b-harper** [comment]
Hey @plembo-arw,

Looking over the imagick changelog, I do see entries about [fixing ZTS](https://github.com/mkoppanen/imagick/blob/master/ChangeLog#L207) so it appears that there is ZTS support.  We'll look into getting zts support added.  Would you be willing to test if we were to get some packages into the testing repos?

-Ben

**Comment by ghost** [comment]
Sure would. I've got at least one test box I could set aside for that.

**Comment by b-harper** [comment]
Updated packages have been built and should trickling into the testing repos today.

**Comment by b-harper** [comment]
Hey @plembo-arw, 

Just checking in and seeing if you have had a chance to look check out the updated packages.

**Comment by b-harper** [comment]
We enabled ZTS support awhile back and forgot to close out this issue.
